### ISSUE TITLE
Edit on GitHub leads to 404

### ISSUE THREAD

**Issue by eben-roux** [canjs/can-define#176] opened 2017-04-19 19:15 UTC
__How often can you reproduce it?__ 

- [ x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

"Edit on GitHub" link broken on [this page](https://canjs.com/doc/can-define/list/list.prototype.filter.html).

__Steps to reproduce:__

![filter-edit-404](https://cloud.githubusercontent.com/assets/5379436/25197668/10d73346-2545-11e7-85f2-08e573d27754.gif)

__Expected results:__

Well... I would've expected to fork the file in order to edit it :)

__Actual results:__

404 error

__Environment:__

| Software                   | Version
| -------------------- | -------
| can-define version   |  n/a
| Browser                    |  chrome
| Operating system    |  win8.1

**Comment by chasenlehara** [comment] 2017-04-20 17:09
@imaustink I think this is a dupe of https://github.com/canjs/bit-docs-html-canjs/issues/204 and should’ve been fixed; could you [redeploy canjs.com](https://canjs.com/doc/guides/contributing/releases.html#Updatingcanjs_com) and see if that fixes it, otherwise look into the issue please?

**Comment by imaustink** [comment] 2017-05-02 00:32
@chasenlehara  Redeploying the site does not fix the issue. I am investigating further.

**Closed** 2017-06-19 17:24 UTC
Labels: developer relations, p1
