### ISSUE TITLE
Provide required properties to a map and throw error if not exact

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-define#119] opened 2016-12-16 22:51 UTC
Based on the below conversation it would be nice to be able to define what properties are needed and a flag for treating it as a strict map that would throw an error if any extra properties are passed (or missing).

```
john
Is there any major performance cost with passing the full app to a component with `{app}="app"` as compared to passing individual fields like: `{user}="app.user" {lane}="app.lane"`?

adam [3:37 PM]  
Unlikely

daffl [3:37 PM]  
I don’t think so. They’re just references.

adam [3:37 PM]  
It is in fact abbot if an anti pattern to pass the app state around, similar to using globals

john [3:37 PM]  
Does it make more sense semantically to all of you to do one over the other?

garrett [3:37 PM]  
Yeah they’re not copies. In bitcentive each component had a reference to the app so you didn’t need to use `attr('%root')` (edited)

adam [3:39 PM]  
I wouldn't use attr('root') for the same reasons I wouldn't use globals, it makes it less isolated, harder to write tests for, and unnessecariky couples the appstate to the component

garrett [3:39 PM]  
Good points

john [3:40 PM]  
k, so split it apart then. I would agree with that. Only coupling and giving each component exactly what it needs.

[3:41]  
If it needs a ref to the full app, give it. Otherwise just pass in the smallest derivitives.

[3:41]  
With this PR I will do an audit on everything. I have seen that we are passing a lot of stuff around that we don’t need.

daffl [3:42 PM]  
It would be really nice if in `define` we could define required properties

[3:42]  
and throw an error if we don’t get them (or something else)

john [3:44 PM]  
Doesn’t 3.0 allow that?
```

**Comment by justinbmeyer** [comment] 2016-12-16 23:43
Closing as duplicate of #62

**Closed by justinbmeyer** 2016-12-16 23:43 UTC
