### ISSUE TITLE
support rest/spread  and for/in loops

### ISSUE THREAD

**Issue by christopherjbaker** [canjs/can-define#199] opened 2017-05-12 21:26 UTC
It would be very convenient if DefineMap instances could be used with the es6 rest and spread operators. These syntaxes only utilize enumerable properties.

```javascript
let { ...rest } = foo;
{ ...foo }
```

**Comment by justinbmeyer** [comment] 2017-05-13 02:19
Can you add a description?

**Comment by justinbmeyer** [comment] 2017-05-23 13:54
This is a duplicate of #34 I think.  I'll close that one.

**Comment by justinbmeyer** [comment] 2018-01-23 18:12
I think `can-observe` has to be the fix for this, unless we bring in a proxy (or slow up can-define) to be less lazy.  Closing b/c I think we should focus on `can-observe`.

**Closed by justinbmeyer** 2018-01-23 18:12 UTC
