### ISSUE TITLE
proto.__set: getter exists but self[prop](value) throws an exception, "not a function"

### ISSUE THREAD

**Issue by agsv83** [canjs/can-define#42] opened 2016-07-28 08:57 UTC
Hi, first of all, thanks for canjs, it's amazing.

I'm creating a computed field like this:

```
adminBlocked : {
                        Value : can.Map,
                        Type : can.Map,
                        value : { 'adminBlocked' : 0, 'adminName' : '' },
                        set : function(newVal, setVal){ 
                          console.log('[adminBlocked][set]');
                          var self = this;
                          if ( 'string' === typeof self.extrasDocumentId){
                            scope.myDB.get(self.extrasDocumentId)
                              .then(function(extrasDoc){ 

                                extrasDoc.adminBlocked = newVal.adminBlocked;
                                extrasDoc.adminName = newVal.adminName;

                                scope.myDB.put(extrasDoc)
                                  .then(function(ret){
                                    console.log('[adminBlocked][set][ret]', ret);
                                    console.log(setVal);
                                    try {
                                      setVal(extrasDoc);
                                    }
                                    catch(err){
                                      console.log('[canError]', err);
                                    }
                                  })
                                  .catch(function(err){
                                    console.log('[adminBlocked][set][err]', err);
                                  });

                              })
                              .catch(function(err){ console.log('Error getting extras doc', err); });
                          }
                        },
                        get : function(lastVal, setAttrValue){
                          console.log('[adminBlocked][get]',lastVal, setAttrValue);
                          var self = this;
                          if ( 'string' === typeof self.extrasDocumentId){
                            scope.myDB.get(self.extrasDocumentId)
                              .then(function(extrasDoc){ 
                                var ret = { 
                                  'adminBlocked' : 'undefined' !== typeof extrasDoc.adminBlocked ? extrasDoc.adminBlocked : 0, 
                                  'adminName' : 'undefined' !== typeof extrasDoc.adminName ? extrasDoc.adminName : '' 
                                };
                                console.log('[adminBlocked][get][ret]', ret);
                                return setAttrValue(new can.Map(ret));
                              })
                              .catch(function(err){ console.log('Error getting extras doc', err); });
                          }
                        },
                        serialize : false
                      },`
```
The get works fine I think, but when I put a value into the attribute I get f[e] is not a function. Downloading the code I've added a log here:

`if (setter) {
                can.batch.start();
                var setterCalled = false, setValue = setter.call(this, value, function (value) {
                        console.log(getter);
                        if (getter) {
                            console.log(prop, self);
                            self[prop](value);
                        } else {
                            oldSet.call(self, prop, value, current, success, errorCallback);
                        }
                        setterCalled = true;`

It outputs "adminBlocked" and an object called __constructor with the fields of the parent Map, but "adminBlocked" is not there, this also happens with other fields of this defined the same way.

As I've seen you have a fallback "oldSet", adding this "if (getter and self[prop])" to the code makes it work as it should.

I don't know if this is a bug or if it is a consequence of not having set something right. Perhaps I did not understand properly how to use the plugin and how to specify the attributes.

**Comment by justinbmeyer** [comment] 2016-07-29 14:07
That's a lot of code to look at.  I want to make sure this issue is in the right place and I'd like to understand what the problem is and what you're trying to do. 

It seems like you are using can.Map with can-map-define.  If this is the case, please move this issue here:  https://github.com/canjs/can-map-define.  This repo, `can-define`, is for the new `define`, `DefineMap`, and `DefineList` modules.

Second, can you pair down the code a bit to give a general example of what you are trying to do.  Also include a high level explination.  Assuming you are using 2.3 code, you can probably create a JSBin:  http://jsbin.com/venaje/1/edit?html,js,output

Closing b/c I'm pretty sure this needs to be removed.  If this is in the right spot, I'll reopen.

**Closed by justinbmeyer** 2016-07-29 14:07 UTC
