### ISSUE TITLE
DefineList.map returns Default Object Type when Default (#) is set

### ISSUE THREAD

**Issue by roemhildtg** [canjs/can-define#153] opened 2017-03-01 20:01 UTC
http://jsbin.com/yuqedinaqe/edit?js,console - open browser console to see issue.

If I define a list like
```javascript
var MyMap = can.DefineMap.extend({
  prop: 'string',
  other: 'string'
})

var MyList = can.DefineList.extend({
  '#': MyMap
});

var list = new MyList([{
  prop: 'test',
  other: 'other test'
}]);

var mapped = list.map(function(item){
  return item.other;
});
```

`mapped` should be a list with a single string in it. Instead, it is an instance of `MyMap`. 

The workaround is to do instead:
```javascript
list.serialize().map(function(item){
    return item.other;
});

**Comment by christopherjbaker** [comment] 2017-04-05 22:01
So it seems that the array resulting from the map (`[ "other list" ]`) is being passed into constructor of that list (`MyList` in this case), each item then being passed through `MyMap`, resulting in a call to `MyMap("other list")`.

While it would be very easy to change this, it seems to be very [intentionally coded this way](https://github.com/canjs/can-define/blob/master/list/list-test.js#L374). If this new behaviour is needed, perhaps we should implement a `.mapRaw()` that returns the same info, but does not wrap it?

**Comment by chasenlehara** [comment] 2017-04-05 22:14
I think I labeled this issue incorrectly. Because what is returned from `.map()` is an instance of `MyList`, and everything in it is supposed to be an instance of `MyMap`, the current behavior seems correct.

**Comment by christopherjbaker** [comment] 2017-04-05 22:17
Since the code is actually working as intended, but clearly the simplified behaviour is desired, should I create the *Raw() methods?

**Comment by chasenlehara** [comment] 2017-04-05 22:19
No, I think the workaround in the original description is the correct thing to do. I’d like to hear @roemhildtg’s feedback before closing this as won’t fix.

**Comment by roemhildtg** [comment] 2017-04-05 23:03
I'm fine with either way tbh. I just think the behavior of `.map()` is generally used to convert an array of objects into a different type of array, which isn't possible without first using `serialize()`. That being said, you have a valid point, and I have a solution to my problem.

**Comment by justinbmeyer** [comment] 2017-04-05 23:21
Map should return a plain DefineList. Filter should return the same type as the source list. Eventually, this should be configurable with the species symbol.

**Comment by christopherjbaker** [comment] 2017-04-05 23:26
Currently, [`.map()`](https://github.com/canjs/can-define/blob/master/list/list.js#L1012) and [`.filter()`](https://github.com/canjs/can-define/blob/master/list/list.js#L968) both return the same type as the source list, and both have tests to that effect.

**Comment by justinbmeyer** [comment] 2017-04-06 00:45
Yeah, map should not do this.

**Closed** 2017-04-13 17:58 UTC
Labels: bug, help wanted, p1
