### ISSUE TITLE
Extending DefineMap constructor functions throws an error

### ISSUE THREAD

**Issue by BigAB** [canjs/can-define#57] opened 2016-09-01 02:15 UTC
`Uncaught TypeError: Cannot redefine property: _data`

https://jsbin.com/zayeba/edit?html,js,output

As per the docs here: https://github.com/canjs/can-define#candefinemapextendname-static-prototype

You should be able to do something like this:

```javascript
const Person = DefineMap.extend({ foo: 'string' });
const Employee = Person.extend({ bar: 'string' });
```

But right now this throws the error above.

**Comment by justinbmeyer** [comment] 2016-09-01 03:13
Closing as duplicate of https://github.com/canjs/can-define/issues/18

**Closed by justinbmeyer** 2016-09-01 03:13 UTC
Labels: bug

**Comment by justinbmeyer** [comment] 2016-09-01 03:17
Let me know if you want to work on this.  I can probably show you what it takes to happen.

**Comment by BigAB** [comment] 2016-09-01 04:00
My only concern with marking this as a duplicate is that #18 is marked as an `enhancement` and I would say this is a `bug` because, as mentioned, it is documented that this is how it should work.
https://github.com/canjs/can-define#candefinemapextendname-static-prototype

**Comment by justinbmeyer** [comment] 2016-09-01 12:38
That issue was created prior to the docs. Please add the bug label if you like.
